#		
#______                     _____           _                 _       
#|  ___|                   |  ___|         | |               | |      
#| |_ _   _ _ __ _ __ _   _| |__ _ __   ___| |__   __ _ _ __ | |_ ___ 
#|  _| | | | '__| '__| | | |  __| '_ \ / __| '_ \ / _` | '_ \| __/ __|
#| | | |_| | |  | |  | |_| | |__| | | | (__| | | | (_| | | | | |_\__ \
#\_|  \__,_|_|  |_|   \__, \____/_| |_|\___|_| |_|\__,_|_| |_|\__|___/
#                      __/ |                                          
#                     |___/                                           
#		
#


#
command-ingame: "§c§l> §r§7Please use this command in-game!"
no-permission: "§c§l> §r§7You don't have permission to use this command!"


#
title: "§5§lENCHANTS MENU"
sword: "§r§b§lSword\n§r§7Click for more"
armor: "§r§b§lArmor\n§r§7Click for more"
tools: "§r§b§lTools\n§r§7Click for more"

#Sword Enchant Section
swordtitle: "§5§lSWORD ENCHANTS"
armortitle: "§5§lARMOR ENCHANTS"
toolstitle: "§5§lTOOLS ENCHANTS"
